version: '3'

services:

  app:
    container_name: wb-app
    build: .
    ports:
      - "8080:80"
    volumes:
     - ./www:/var/www/html
    links:
      - db
      - phpmyadmin

  db:
    image: mysql
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wbms
    ports:
     - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8081:80
    volumes:
      - /sessions